# Generated by Django 4.2.21 on 2025-05-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_items',
        ),
    ]
